API_TOKEN = 'XXX'
ID_ACCOUNT = 7777
ID_PAYMENT = 111

DB_FILENAME = 'bot_users_and_files.db'
URL_CHAT = 'https://t.me/'
APP_NAME = ''
URL_MANE_CONTACT = 'https://t.me/'
MANE_CONTACT = ''

BANNERS = {
    'banner_1': 'AgACAgIAAxkDAAIBB2FTpx7npX8AAUL2OFhclb9NCLVOxgACxbQxG8ZzeEpJgksaIcdC6QEAAwIAA3cAAyEE',
    'banner_2': 'AgACAgIAAxkDAAIBAmFTpx09Ssz8ZiVV4nK1Mli5byRgAALCtDEbxnN4Spslut0donFMAQADAgADdwADIQQ',
    'banner_3': 'AgACAgIAAxkDAAIBA2FTpx0Rz9iztT0ucPzmh8As1_w6AALDtDEbxnN4SvEEcVrO_7xYAQADAgADdwADIQQ',
    'banner_4': 'AgACAgIAAxkDAAP-YVOnHBbBuryOpC9rbaiyKIyGP34AAsC0MRvGc3hKIxDriNSm8F0BAAMCAAN3AAMhBA',
    'banner_5': 'AgACAgIAAxkDAAIBAAFhU6ccuyZxWYjJZneu1Mo0voVMtgACwbQxG8ZzeErNHqlANOWTZAEAAwIAA3cAAyEE',
    'banner_6': 'AgACAgIAAxkDAAIBCWFTpx-T0p_3v75AdHgdsU3lEZLRAALGtDEbxnN4Si0dlndk2J7EAQADAgADdwADIQQ',
    'banner_7': 'AgACAgIAAxkDAAIBC2FTpx_PwoI_T2nIGd5ol3L1x3PyAALHtDEbxnN4SnMHwISYwMsLAQADAgADdwADIQQ',
    'banner_8': 'AgACAgIAAxkDAAIBBWFTpx3PbOFY_wxo8F-BqFV5kD4pAALEtDEbxnN4Sqa4z0qysRajAQADAgADdwADIQQ',
    'avatar': 'AgACAgIAAxkDAAIBDWFTpyBVPz97tCAZDCepD9Vc4gSoAALItDEbxnN4SmNGHBxVeOJEAQADAgADeQADIQQ'
}

