API_TOKEN = 'XXX'
ID_ACCOUNT = 77777
DB_FILENAME = 'load_files.db'
URL_CHAT = ''
APP_NAME = 'Economic Bot'
URL_MANE_CONTACT = ''
MANE_CONTACT = ''
BANNERS = {
    'banner_1': 'AgACAgIAAxkDAAM9YU9FwVrx-WI6imhCfNPUdNldYAQAAsW0MRvGc3hKSYJLGiHHQukBAAMCAAN3AAMhBA',
    'banner_2': 'AgACAgIAAxkDAAM6YU9FwIdY0VIXvsQYNHeDaoxjDkgAAsK0MRvGc3hKmyW63R2icUwBAAMCAAN3AAMhBA',
    'banner_3': 'AgACAgIAAxkDAAM7YU9FwDpj0VIbPPmwDNueRuEnvegAAsO0MRvGc3hK8QRxWs7_vFgBAAMCAAN3AAMhBA',
    'banner_4': 'AgACAgIAAxkDAAM4YU9FvyioZ-BIslJqHstOrE1jIIkAAsC0MRvGc3hKIxDriNSm8F0BAAMCAAN3AAMhBA',
    'banner_5': 'AgACAgIAAxkDAAM5YU9FwPMHqROO5xuQJrwezTk0yYoAAsG0MRvGc3hKzR6pQDTlk2QBAAMCAAN3AAMhBA',
    'banner_6': 'AgACAgIAAxkDAAM-YU9FwcXpKOTHW-fYtUthNbYeGaMAAsa0MRvGc3hKLR2Wd2TYnsQBAAMCAAN3AAMhBA',
    'banner_7': 'AgACAgIAAxkDAAM_YU9Fwv19S0RyuXyfrMWO4EkSWd8AAse0MRvGc3hKcwfAhJjAywsBAAMCAAN3AAMhBA',
    'banner_8': 'AgACAgIAAxkDAAM8YU9FwZzb_X9d_RKnuVeFe-RcSvYAAsS0MRvGc3hKprjPSrKxFqMBAAMCAAN3AAMhBA',
    'avatar': 'AgACAgIAAxkDAANAYU9FwkgTQabS9JROOKaJFkBBN4IAAsi0MRvGc3hKY0YcHFV44kQBAAMCAAN5AAMhBA'
}

